version: '3'

services:

  nginx:
    container_name: nginx_server
    image: nginx
    volumes:
      - ./web:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    ports:
      - "80:80"
  db:
    container_name: db_server
    image: mysql    
    volumes:
      - ./data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=sev1234
  php:
    build: php/
    container_name: php
    volumes:
      - ./web:/var/www/html
    

